import React from "react";

export default function KeywordListPage() {
  const digitalKeywords = [
    // Web dev, Graphic, Branding, Social Media, Flex banners focused, no app dev keywords
    "Digital services company",
    "Graphic design services",
    "Logo design agency",
    "Professional branding solutions",
    "Creative banner design",
    "Brochure design company",
    "Flyer design services",
    "Video editing company",
    "3D animation studio",
    "Explainer video makers",
    "Motion graphics designer",
    "Social media marketing agency",
    "Facebook ads expert",
    "Instagram promotion service",
    "YouTube channel setup",
    "Google Ads manager",
    "SEO expert services",
    "Search engine optimization company",
    "Website development company",
    "Web design studio",
    "Responsive website design",
    "Ecommerce web development",
    "Shopify experts India",
    "WooCommerce store developers",
    // Removed app development keywords here
    "UI/UX design agency",
    "WhatsApp marketing solutions",
    "Email marketing automation",
    "Product photography service",
    "Ecommerce photography studio",
    "Model photo shoot",
    "White background product photo",
    "Background removal service",
    "Green screen video service",
    "Domain registration India",
    "Hosting and SSL service",
    "Google My Business SEO",
    "Business profile optimization",
    "Local SEO expert",
    "Website speed optimization",
    "Lead generation expert",
    "CRM integration services",
    "Chatbot integration",
    "Landing page design",
    "Custom contact form",
    "Newsletter design",
    "YouTube video thumbnails",
    "YouTube content marketing",
    "Digital content writing",
    "Blog writing service",
    "Copywriting for ads",
    "Hashtag strategy for Instagram",
    "Digital marketing agency India",
    "Online branding service",
    "Influencer marketing setup",
    "Facebook page management",
    "Instagram reels creation",
    "Animated logo design",
    "Product explainer videos",
    "Software UI design",
    "Application mockups",
    "Figma designer India",
    "Email newsletter campaign",
    "Business automation tools",
    "Payment gateway setup",
    "Google analytics integration",
    "Meta pixel setup",
    "Retargeting ad setup",
    "Social media scheduling",
    "Branding consultancy",
    "Ecommerce strategy consulting",
    "Conversion rate optimization",
    "Online portfolio creation",
    "Resume website builder",
    "School website design",
    "Booking website development",
    "Directory website setup",
    "Dropshipping store setup",
    "Multi-vendor store development",
    "Mobile friendly design",
    "Website audit services",
    "Performance marketing expert",
    "PPC ads consultant",
    "WhatsApp catalog setup",
    "Voice-over video service",
    "Scriptwriting for videos",
    "UI animations",
    "Interaction design",
    "Custom website features",
    "Company profile presentation",
    "Google forms integration",
    "Testimonial video editing",
    "Service brochure PDF design",
    "HR software integration",
    "Event promotion digitally",
    "Virtual assistant services",
    // Added focus keywords explicitly
    "Web development",
    "Graphic design",
    "Branding",
    "Social media design",
    "Flex banners",
    "Flex banner design",
    "Flex banner printing"
  ];

  const printingKeywords = [
    "Printing services near me",
    "Offset printing company",
    "Flex banner printing",
    "Vinyl printing shop",
    "Glow sign board printing",
    "LED signboard manufacturer",
    "Backlit board printing",
    "Sunboard printing",
    "Foam board printing",
    "Canvas printing service",
    "Roll up standee printing",
    "Poster printing service",
    "Event backdrop printing",
    "Custom t-shirt printing",
    "Mug printing online",
    "Cap printing service",
    "Personalized gift printing",
    "Sublimation printing",
    "Screen printing on clothes",
    "UV printing on acrylic",
    "Visiting card printing",
    "Business card printing",
    "Premium card printing",
    "Foil stamped card",
    "Embossed business card",
    "Invitation card printing",
    "Wedding card printing",
    "Event card printing",
    "Birthday invitation printing",
    "Menu card printing",
    "Table tent card printing",
    "Restaurant menu printing",
    "Calendar printing",
    "Table calendar printing",
    "Wall calendar design",
    "Customized diary printing",
    "Notebook printing service",
    "Envelope printing",
    "Letterhead printing",
    "Invoice book printing",
    "Bill book printing",
    "Receipt book printing",
    "Barcode label printing",
    "Sticker printing service",
    "Waterproof label printing",
    "Hologram label printing",
    "Product label printing",
    "QR code sticker printing",
    "School ID card printing",
    "Employee ID badge",
    "Plastic ID card printing",
    "Lanyard printing company",
    "Pen printing with logo",
    "Corporate gift printing",
    "Brochure printing service",
    "Flyer printing shop",
    "Catalog printing online",
    "Magazine printing services",
    "Newsletters printing",
    "Custom packaging box print",
    "Mono carton box printing",
    "Food packaging print",
    "Pharma label printing",
    "Cosmetic label design",
    "Die cut sticker printing",
    "A4 document printing",
    "Legal size printouts",
    "Spiral binding & print",
    "Thesis printing and binding",
    "Certificate printing shop",
    "School project printing",
    "Educational charts printing",
    "Laminated card printing",
    "Transparent card printing",
    "ID holder printing",
    "Tent card with logo",
    "Pop up banner print",
    "Hanging banner print",
    "Fabric printing services",
    "Canvas bag printing",
    "Eco-friendly bag printing",
    "Paper bag with logo",
    "Gift bag printing",
    "Event branding print",
    "Office branding board",
    "Vehicle wrap printing",
    "Shop name board",
    "Acrylic name plate print",
    "House name plate printing",
    "Office door sign print",
    "Door hanger printing",
    "Resume printing service",
    "Greeting card printing",
    "Corporate invitation printing",
    "Real estate brochure print",
    "Roll form label printing",
    "Transparent vinyl sticker",
    "Glow-in-dark printing",
    "Number plate sticker print",
    "Industrial tag printing"
  ];

  // Merge and remove duplicates:
  const allKeywordsSet = new Set([...digitalKeywords, ...printingKeywords]);
  const allKeywords = Array.from(allKeywordsSet);

  return (
    <div className="p-6 bg-white text-gray-900">
      <h1 className="text-4xl font-bold text-center mb-10 text-green-700">
        Ultimate Digital & Printing Services - AR Print Hub
      </h1>

      {/* 4 column grid on desktop, 2 on mobile */}
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-6">
        {allKeywords.map((keyword, index) => (
          <div
            key={index}
            className="border border-gray-300 rounded p-3 bg-gray-50 text-gray-800"
          >
            {keyword}
          </div>
        ))}
      </div>
    </div>
  );
}
